### ISSUE TITLE
Printing is repeated, after tapping Enter or Space

### ISSUE THREAD

**Issue by hschell-cortado** [ezeep/ezeep-js#45]
[](https://jira.thinprint.de/secure/attachment/170034/170034_Successfully+printed1.png)Print via Print Now. After printing's succeeded, an alert dialogue overlaying the Print Now GUI appears:

Tap Enter or Space (to close the dialogue):
The file will be printed again.

**Comment by hschell-cortado** [comment]
![image](https://user-images.githubusercontent.com/84859936/157630362-620be814-433c-4275-8ed3-aaf2557d367f.png)

**Comment by JosephHolz** [comment]
I think it could be a good idea to change the confirmation message – instead of "successfully printed" >>> "Successfully sent to printer."
This has the advantage that someone who prints via the AnyPrinter queue doesn't think that their print job was immediately released

**Comment by hschell-cortado** [comment]
@cms-benjamin-schueler what do you think?

**Comment by cms-benjamin-schueler** [comment]
The success message should be different in the case of a printer with the "is_queue" attribute such as the AnyPrinter. In our mobile clients we use a message such as "Ready to be released.".

**Comment by cgoern** [comment]
Remove focus from print button & disable it while printing to prevent repeated printing: f1762d4
